// <auto-generated />
using Data.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230326175215_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("Cuisines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Italian",
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "French",
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Japanese",
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("Data.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A classic Italian pizza",
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A classic French bistro",
                            Name = "French Bistro"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A trendy Japanese sushi bar",
                            Name = "Sushi Bar"
                        });
                });

            modelBuilder.Entity("Data.Entities.Cuisine", b =>
                {
                    b.HasOne("Data.Entities.Restaurant", "Restaurant")
                        .WithOne("Cuisine")
                        .HasForeignKey("Data.Entities.Cuisine", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Data.Entities.Restaurant", b =>
                {
                    b.Navigation("Cuisine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
